### PR TITLE
Haptic feedback

### PR DESCRIPTION
**Pull request by rodydavis**

### CODE REVIEW

**Comment by rodydavis** [comment]
Adding Haptic Feedback to iOS and Android

**Comment by clovisnicolas** [comment]
Hello,
Thanks for the PR this looks great. Could you revert some of your changes to the LICENSE, pubspec, README so that we can merge this ? Or do you plan to publish your own package?

**Comment by rodydavis** [comment]
Sorry I will do that. I was originally doing a PR for my master but it did yours. I will update the info for the PR to the master branch of yours. I would rather not publish my own since it's so similar. Any other changes needed?

Rody Davis Jr.
Full Stack Mobile Developer
Github | Website | Appstore | LinkedIn
Twitter | Facebook | YouTube

**Comment by clovisnicolas** [comment]
Maybe revert the few "com.appleeducate" => "flutter.plugins.vibrate", but the rest of the code looks great to me, i'll just try it on a device later and merge it

**Comment by rodydavis** [comment]
@clovisnicolas ok changes made!

**Comment by rodydavis** [comment]
So far I have tested with Google Pixel, iPhone X, and Simulator iPhone X.

Important Notes: Haptic Feedback is only available on iOS 10 and later, I fall back to the default vibrate if it is not available. I also added a simulator check because it cannot vibrate there.

**Pull request merged**
